spring:
    application:
        name: user-service

    datasource:
        driver-class-name: org.postgresql.Driver
        initialization-mode: always
        platform: postgres
        url: ${DB_PATH:jdbc:postgresql://localhost:5432/rentacar}
        username: postgres
        password: 1234

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation=true
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8081

security:
    jwt:
        token:
            secret-key: SECRET_KEY
            expire-length: 30000000000

