server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - name: PreFilter
            - RewritePath=/user-service/(?<path>.*), /$\{path}

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search-service/**
          filters:
            - name: PreFilter
            - RewritePath=/search-service/(?<path>.*), /$\{path}

        - id: advertisement-service
          uri: lb://advertisement-service
          predicates:
            - Path=/advertisement-service/**
          filters:
            - name: PreFilter
            - RewritePath=/advertisement-service/(?<path>.*), /$\{path}

        - id: administrator-service
          uri: lb://administrator-service
          predicates:
            - Path=/administrator-service/**
          filters:
            - name: PreFilter
            - RewritePath=/administrator-service/(?<path>.*), /$\{path}

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message-service/**
          filters:
            - name: PreFilter
            - RewritePath=/message-service/(?<path>.*), /$\{path}
