version: '3'
services:

  consul-server:
    image: consul-server
    build:
      context: ./consul-server
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8500:8500"
    networks:
      static-network:
        ipv4_address: 172.20.0.2
    
  user-service:
    image: user-service
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    environment:
      DB_PATH: jdbc:postgresql://postgres/rentacar
    depends_on:
      - consul-server
      - postgres
    links:
      - postgres
      
  search-service:
    image: search-service
    build:
      context: ./services/search-service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    environment:
      DB_PATH: jdbc:postgresql://postgres/rentacar
    depends_on:
      - consul-server
      - postgres
    links:
      - postgres

  advertisement-service:
    image: advertisement-service
    build:
      context: ./services/advertisement-service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    environment:
      DB_PATH: jdbc:postgresql://postgres/rentacar
    depends_on:
      - consul-server
      - postgres
    links:
      - postgres
      
  message-service:
    image: message-service
    build:
      context: ./services/message-service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    environment:
      DB_PATH: jdbc:postgresql://postgres/rentacar
    depends_on:
      - consul-server
      - postgres
    links:
      - postgres
      
  administrator-service:
    image: administrator-service
    build:
      context: ./services/administrator-service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    environment:
      DB_PATH: jdbc:postgresql://postgres/rentacar
    depends_on:
      - consul-server
      - postgres
    links:
      - postgres

  gateway:
    image: gateway
    build:
      context: ./services/Gateway
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8080:8080"
    networks:
      - static-network
    depends_on:
      - consul-server 
      
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
        - 5432
    ports:
        - 5400:5432
    networks:
        - static-network
    environment:
        - POSTGRES_PASSWORD=1234
        - POSTGRES_USER=postgres
        - POSTGRES_DB=rentacar
    restart: unless-stopped
    depends_on:
        - consul-server

volumes:
  postgres-data:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16