//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 01:08:46 AM CEST 
//


package com.rentacar.administratorservice.ws.company;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rentacar.administratorservice.ws.company package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rentacar.administratorservice.ws.company
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterCompanyResponse }
     * 
     */
    public RegisterCompanyResponse createRegisterCompanyResponse() {
        return new RegisterCompanyResponse();
    }

    /**
     * Create an instance of {@link RegisterCompanyRequest }
     * 
     */
    public RegisterCompanyRequest createRegisterCompanyRequest() {
        return new RegisterCompanyRequest();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

}
