//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 11:31:28 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.administratorservice.rentacar.com/ws/company", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.rentacar.administratorservice.ws.company;
