spring:
    application:
        name: search-service

    datasource:
        driver-class-name: org.postgresql.Driver
        initialization-mode: never
        platform: postgres
        url: jdbc:postgresql://localhost:5432/rentacar
        username: postgres
        password: 1234

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation=true
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8085

