spring:
    application:
        name: advertisement-service

    datasource:
        driver-class-name: org.postgresql.Driver
        initialization-mode: never
        platform: postgres
        url: ${DB_PATH:jdbc:postgresql://localhost:5432/rentacar}
        username: postgres
        password: 1234

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation=true
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8083

